version: "3"

services:
  aapanel:
    build: 
      context: ./bin/aapanel
    container_name: "aapanel-webserver"
    ports:
      - "6321:7800"
      - "6322:80"
      - "6323:443"
      - "6324:888"
      - "6325:6379"
    volumes: 
      - website_data:/www/wwwroot
      - website_log:/www/wwwlogs
    ulimits:
      nofile:
        name: nofile
        hard: 65535
        soft: 65535

volumes:
  website_data:
    driver: local
  website_log:
    driver: local
